### PR TITLE
Fix error when login Growtopia Private Server

### PR DESCRIPTION
**Pull request by GuckTubeYT**

### CODE REVIEW

**Comment by NabsiDevv** [comment]
this would remove a feature fully you should make a bool and then checkbox to disable inventory logging for certain time.

**Comment by GuckTubeYT** [comment]
> this would remove a feature fully you should make a bool and then checkbox to disable inventory logging for certain time.

okay, i will try it

**Comment by GuckTubeYT** [comment]
but, i am using visual studio code to build c#, and i cant to add the checkbox

**Comment by playingoDEERUX** [comment]
I did it. Check V2.3.1 and look at config, there it will say 'Disable Inventory Serialization' to fix private server joining!

**Pull request closed without merging**
